research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

translate_task:
  description: >
    Translate the information to Brazilian Portuguese
  expected_output: >
    A fully translated report in Brazilian Portuguese
    Formated as markdown with out '```'

publish_task:
  description: >
    Post the fully translated report to the WordPress blog.
    The content is stored in the file 'report_ptbr.md'.
  expected_output: >
    The report should be published to the WordPress blog with the appropriate title, tags, and content.
  agent: blog_publisher
