[project]
name = "surprise_travel"
version = "0.1.0"
description = "surprise-travel using crewAI"
authors = [{name = "Your Name", email = "you@example.com"}]
requires-python = ">=3.10,<=3.13"
dependencies = [
    "crewai[tools]>=0.152.0",
    "crewai-tools>=0.58.0",
]

[project.scripts]
surprise_travel = "surprise_travel.main:run"
train = "surprise_travel.main:train"
