[project]
name = "exam_prep"
version = "0.1.0"
description = "exam_prep using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.114.0,<1.0.0",
    "google-api-python-client>=2.0.0",
    "python-dotenv>=0.19.0"
]

[project.scripts]
exam_prep = "exam_prep.main:run"
run_crew = "exam_prep.main:run"
train = "exam_prep.main:train"
replay = "exam_prep.main:replay"
test = "exam_prep.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
